# multiclass Logistic Regression

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [39]:
from sklearn.datasets import make_classification

In [40]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=4, random_state=42)

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [42]:
y_test

array([3, 1, 0, 2, 1, 2, 2, 1, 2, 2, 3, 0, 3, 2, 0, 3, 3, 3, 1, 1, 0, 3,
       2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 3, 2, 1, 0, 2, 1, 2, 1, 0,
       1, 1, 0, 2, 1, 3, 1, 3, 1, 2, 3, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 3,
       2, 2, 1, 1, 3, 1, 2, 0, 0, 1, 2, 1, 3, 2, 3, 1, 3, 3, 3, 1, 2, 2,
       3, 1, 1, 2, 0, 1, 3, 0, 3, 1, 2, 0, 0, 3, 2, 2, 1, 1, 3, 3, 3, 2,
       3, 0, 2, 2, 3, 1, 3, 2, 3, 0, 1, 2, 0, 1, 2, 3, 0, 3, 3, 3, 3, 0,
       3, 1, 3, 2, 2, 3, 2, 3, 3, 1, 1, 3, 0, 2, 3, 3, 0, 0, 1, 2, 3, 3,
       1, 2, 3, 1, 0, 3, 2, 2, 2, 1, 2, 0, 2, 3, 3, 0, 0, 2, 0, 3, 2, 0,
       1, 1, 1, 3, 2, 1, 3, 2, 2, 0, 1, 3, 2, 2, 3, 0, 2, 3, 2, 1, 0, 2,
       0, 2, 1, 1, 3, 2, 3, 0, 3, 1, 2, 0, 2, 1, 2, 0, 3, 2, 3, 1, 3, 0,
       1, 0, 0, 3, 1, 2, 0, 3, 0, 3, 1, 0, 2, 3, 3, 1, 0, 3, 1, 2, 1, 0,
       1, 0, 3, 2, 1, 1, 2, 0])

In [43]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')

In [44]:
logistic.fit(X_train, y_train)

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [45]:
y_pred = logistic.predict(X_test)
y_pred

array([3, 1, 0, 2, 1, 2, 2, 3, 2, 2, 1, 1, 3, 2, 0, 3, 3, 3, 1, 1, 0, 3,
       2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 3, 2, 0, 0, 2, 1, 2, 0, 0,
       1, 1, 0, 0, 1, 3, 0, 3, 3, 2, 1, 1, 2, 2, 1, 2, 1, 0, 2, 2, 2, 3,
       3, 2, 1, 1, 3, 1, 3, 0, 0, 1, 2, 1, 3, 2, 3, 2, 3, 2, 3, 1, 3, 0,
       3, 3, 1, 3, 0, 1, 3, 0, 3, 1, 0, 0, 0, 3, 2, 2, 1, 1, 3, 3, 3, 2,
       2, 0, 2, 2, 3, 3, 2, 2, 3, 0, 0, 2, 2, 1, 3, 2, 0, 3, 3, 3, 3, 0,
       1, 1, 3, 3, 2, 1, 2, 3, 3, 1, 1, 3, 0, 2, 3, 3, 0, 0, 1, 2, 3, 3,
       1, 2, 1, 1, 0, 3, 2, 2, 0, 1, 2, 0, 2, 0, 3, 0, 0, 2, 0, 3, 2, 0,
       3, 1, 1, 3, 0, 1, 3, 2, 2, 0, 1, 1, 3, 2, 3, 0, 2, 3, 3, 1, 0, 2,
       1, 2, 1, 1, 2, 2, 3, 0, 3, 1, 2, 0, 2, 1, 2, 0, 3, 0, 3, 2, 3, 0,
       1, 0, 0, 3, 1, 2, 0, 3, 0, 3, 1, 0, 2, 3, 3, 1, 2, 3, 1, 2, 1, 0,
       1, 0, 3, 2, 1, 1, 2, 0])

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.832
[[47  2  2  0]
 [ 4 51  2  5]
 [ 7  0 55  8]
 [ 1  6  5 55]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.85        51
           1       0.86      0.82      0.84        62
           2       0.86      0.79      0.82        70
           3       0.81      0.82      0.81        67

    accuracy                           0.83       250
   macro avg       0.83      0.84      0.83       250
weighted avg       0.83      0.83      0.83       250

