In [1]:
import numpy as np

### Task N1: Even-Odd Masking

In [7]:
arr = np.array(np.random.randint(1,100,20))
arr

array([19, 32, 94, 94, 37, 10, 66, 57, 43, 53, 56, 58, 67, 52, 63, 47, 60,
       46, 45, 86], dtype=int32)

In [9]:
arr[arr%2 == 0] = 0
arr

array([19,  0,  0,  0, 37,  0,  0, 57, 43, 53,  0,  0, 67,  0, 63, 47,  0,
        0, 45,  0], dtype=int32)

In [10]:
np.count_nonzero(arr%2 == 1)

np.int64(9)

In [13]:
arr[arr%2 == 0].size

11

### Task N2: Indexing Practice

In [14]:
arr2 = np.arange(1, 21)

In [15]:
arr2[0:5]

array([1, 2, 3, 4, 5])

In [16]:
arr2[-5:]

array([16, 17, 18, 19, 20])

In [18]:
arr2[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
arr3 = arr2[::-1]
arr3

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

### Task N3: Basic Statistics

In [25]:
arr = np.random.randint(1, 100, 15)
arr

array([18, 93,  3, 13, 31, 58, 10, 37, 30, 88, 52, 36, 76, 25, 49],
      dtype=int32)

In [26]:
print(arr.mean(), arr.std(), arr.var())

41.266666666666666 26.891055927369028 723.1288888888889


In [27]:
np.median(arr)

np.float64(36.0)

In [ ]:
arr.max(), arr.min() # max and min

(np.int32(93), np.int32(3))

In [ ]:
arr.argmax(), arr.argmin() # index for max and min

(np.int64(1), np.int64(2))

### 🟢 Task N4: Reshaping

In [31]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr = arr.reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
arr.flatten()
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
arr.ravel()
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 🟢 Task N5: Row vs Column Sum

In [45]:
arr = np.random.randint(1, 10, (4, 4))
arr

array([[2, 3, 8, 1],
       [2, 6, 9, 8],
       [5, 2, 1, 3],
       [3, 4, 1, 1]], dtype=int32)

In [ ]:
arr.sum(axis=1) #row wise sum

array([14, 25, 11,  9])

In [ ]:
arr.sum(axis=0) # column wise sum

array([12, 15, 19, 13])

In [ ]:
arr.sum() # total sum

np.int64(59)

### 🟢 Task N6: Conditional Selection

In [55]:
arr = np.random.randint(1,100,100)

In [56]:
arr2 = arr[arr > 30]
arr2, arr2.size

(array([48, 54, 34, 35, 97, 88, 78, 68, 45, 64, 71, 94, 72, 95, 33, 69, 69,
        75, 43, 46, 50, 92, 54, 82, 51, 86, 78, 98, 76, 59, 37, 51, 82, 50,
        50, 88, 95, 42, 87, 88, 55, 81, 72, 97, 71, 40, 61, 57, 35, 96, 77,
        78, 83, 40, 80, 59, 85, 58, 48, 92, 43, 53, 48, 63, 60, 78, 37, 43,
        54, 44, 75], dtype=int32),
 71)

In [60]:
arr3 = arr[(arr > 20) & (arr < 50)]
arr3, arr3.size

(array([48, 34, 35, 30, 30, 45, 33, 43, 46, 25, 37, 25, 29, 22, 42, 21, 40,
        35, 40, 48, 26, 43, 24, 26, 48, 37, 43, 44], dtype=int32),
 28)

### 🟢 Task N7: Array Comparison

In [65]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([1,2,63,4,8,66,788,89,9])

In [68]:
matches = (arr1 == arr2)
matches

array([ True,  True, False,  True, False, False, False, False,  True])

In [69]:
count = (arr1 == arr2).sum()
count

np.int64(4)

In [71]:
#checking regardless of index

common = np.intersect1d(arr1, arr2)
common, common.size

(array([1, 2, 4, 8, 9]), 5)

### 🟢 Task N8: Manual Normalization Practice

In [79]:
arr = np.random.randint(1,101, 20)
arr

array([68, 88,  4, 14, 92, 73, 91, 57, 41,  6, 38, 27, 95, 74, 68, 78, 73,
       96, 67, 37], dtype=int32)

In [80]:
# min max normalization

arr = (arr - arr.min()) / (arr.max() - arr.min())
arr

array([0.69565217, 0.91304348, 0.        , 0.10869565, 0.95652174,
       0.75      , 0.94565217, 0.57608696, 0.40217391, 0.02173913,
       0.36956522, 0.25      , 0.98913043, 0.76086957, 0.69565217,
       0.80434783, 0.75      , 1.        , 0.68478261, 0.35869565])

In [81]:
arr = arr * 100
arr

array([ 69.56521739,  91.30434783,   0.        ,  10.86956522,
        95.65217391,  75.        ,  94.56521739,  57.60869565,
        40.2173913 ,   2.17391304,  36.95652174,  25.        ,
        98.91304348,  76.08695652,  69.56521739,  80.43478261,
        75.        , 100.        ,  68.47826087,  35.86956522])