In [13]:
import numpy as np
import pandas as pd
import seaborn as sns

In [14]:
from sklearn.datasets import make_classification

In [15]:
X, y = make_classification(n_samples = 1000, n_features=3, n_classes=2, n_redundant=1, random_state=42)
X

array([[ 2.48547786,  2.39963589, -1.46526917],
       [ 2.20403962, -1.06965652,  0.00979545],
       [-0.5726534 , -0.75494788,  0.42032991],
       ...,
       [-0.41608875,  0.46668963, -0.11024494],
       [-1.57936997,  2.48498245, -0.71060102],
       [-0.43277356,  0.89093028, -0.28069604]], shape=(1000, 3))

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred = knn.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [21]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[156   9]
 [ 18 147]]
0.9181818181818182
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       165
           1       0.94      0.89      0.92       165

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330



In [23]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11,15,21,33],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}

In [24]:
grid = GridSearchCV(KNeighborsClassifier(), param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid.fit(X_train, y_train)

c:\Users\soumi\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2885: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [3, 5, 7, 9, 11, 15, 21, 33],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [25]:
grid.best_params_

{'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}

In [26]:
y_pred2 = grid.predict(X_test)

In [28]:
print(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[156   9]
 [ 17 148]]
0.9212121212121213
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       165
           1       0.94      0.90      0.92       165

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330

